show databases;
use login_user_db;
SHOW TABLES;

CREATE TABLE USER_CRED (
ID VARCHAR(50) PRIMARY KEY,
USER_ID VARCHAR(40) UNIQUE NOT NULL,
PASSWORD VARCHAR(80) NOT NULL,
STATUS VARCHAR(20) NOT NULL,
ROLE VARCHAR(20) NOT NULL
	);

INSERT INTO USER_CRED (ID, USER_ID, PASSWORD, STATUS, ROLE)
	VALUES ('2','x11235','password2','DRAFT','ADMIN');

SELECT * FROM USER_CRED;

SELECT * FROM USER_DRAFT_TOKEN;
DELETE FROM USER_DRAFT_TOKEN WHERE USER_ID = 'x11235';


CREATE TABLE USER_DRAFT_TOKEN(
	USER_ID VARCHAR(40) UNIQUE NOT NULL,
	TOKEN VARCHAR(100) UNIQUE NOT NULL
);

DESCRIBE USER_DRAFT_TOKEN;

DROP TABLE USER_DRAFT_TOKEN;